# Generated by Django 4.2.3 on 2025-12-27 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='product',
            name='location',
        ),
        migrations.RemoveField(
            model_name='product',
            name='max_people',
        ),
        migrations.RemoveField(
            model_name='product',
            name='min_people',
        ),
        migrations.RemoveField(
            model_name='product',
            name='unit',
        ),
        migrations.AddField(
            model_name='product',
            name='availability',
            field=models.CharField(choices=[('available', 'Available'), ('unavailable', 'Unavailable'), ('sold_out', 'Sold Out'), ('pre_sale', 'Pre Sale')], default='available', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_available',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
