--
-- PostgreSQL database dump
--

\restrict eR8gw9mTIuUObB35tTI4h5ZQYRLLy0iPqwh21Dm6WDxRCQIoGwmFxq5aQVdv4hP

-- Dumped from database version 16.11 (Debian 16.11-1.pgdg13+1)
-- Dumped by pg_dump version 16.11 (Debian 16.11-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: thamjid
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO thamjid;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: thamjid
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: thamjid
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO thamjid;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: thamjid
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: thamjid
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO thamjid;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: thamjid
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: authentication_user; Type: TABLE; Schema: public; Owner: thamjid
--

CREATE TABLE public.authentication_user (
    id bigint NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    is_active boolean NOT NULL,
    is_deleted boolean NOT NULL,
    username character varying(50) NOT NULL,
    full_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    phone character varying(50) NOT NULL,
    gender character varying(1),
    avatar character varying(100),
    is_staff boolean NOT NULL,
    reset_token character varying(64)
);


ALTER TABLE public.authentication_user OWNER TO thamjid;

--
-- Name: authentication_user_groups; Type: TABLE; Schema: public; Owner: thamjid
--

CREATE TABLE public.authentication_user_groups (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.authentication_user_groups OWNER TO thamjid;

--
-- Name: authentication_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: thamjid
--

ALTER TABLE public.authentication_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.authentication_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: authentication_user_id_seq; Type: SEQUENCE; Schema: public; Owner: thamjid
--

ALTER TABLE public.authentication_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.authentication_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: authentication_user_user_permissions; Type: TABLE; Schema: public; Owner: thamjid
--

CREATE TABLE public.authentication_user_user_permissions (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.authentication_user_user_permissions OWNER TO thamjid;

--
-- Name: authentication_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: thamjid
--

ALTER TABLE public.authentication_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.authentication_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: bookings_booking; Type: TABLE; Schema: public; Owner: thamjid
--

CREATE TABLE public.bookings_booking (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    is_active boolean NOT NULL,
    is_deleted boolean NOT NULL,
    booking_number character varying(50) NOT NULL,
    booking_date date NOT NULL,
    booking_time time without time zone,
    number_of_products integer NOT NULL,
    status character varying(24) NOT NULL,
    payment_status character varying(24) NOT NULL,
    subtotal numeric(10,2) NOT NULL,
    tax numeric(10,2) NOT NULL,
    total_amount numeric(10,2) NOT NULL,
    special_requests text,
    admin_notes text,
    order_id bigint,
    user_id bigint,
    CONSTRAINT bookings_booking_number_of_products_f1b2114b_check CHECK ((number_of_products >= 0))
);


ALTER TABLE public.bookings_booking OWNER TO thamjid;

--
-- Name: bookings_booking_id_seq; Type: SEQUENCE; Schema: public; Owner: thamjid
--

ALTER TABLE public.bookings_booking ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.bookings_booking_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: bookings_payment; Type: TABLE; Schema: public; Owner: thamjid
--

CREATE TABLE public.bookings_payment (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    amount numeric(10,2) NOT NULL,
    payment_method character varying(24) NOT NULL,
    payment_status character varying(24) NOT NULL,
    transaction_id character varying(100),
    session_id character varying(200),
    payment_date timestamp with time zone NOT NULL,
    notes text,
    booking_id bigint NOT NULL
);


ALTER TABLE public.bookings_payment OWNER TO thamjid;

--
-- Name: bookings_payment_id_seq; Type: SEQUENCE; Schema: public; Owner: thamjid
--

ALTER TABLE public.bookings_payment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.bookings_payment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: carts_cart; Type: TABLE; Schema: public; Owner: thamjid
--

CREATE TABLE public.carts_cart (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    is_active boolean NOT NULL,
    is_deleted boolean NOT NULL,
    session_id character varying(100),
    status character varying(24) NOT NULL,
    subtotal numeric(10,2) NOT NULL,
    tax numeric(10,2) NOT NULL,
    total_amount numeric(10,2) NOT NULL,
    expires_at timestamp with time zone,
    last_activity timestamp with time zone NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.carts_cart OWNER TO thamjid;

--
-- Name: carts_cart_id_seq; Type: SEQUENCE; Schema: public; Owner: thamjid
--

ALTER TABLE public.carts_cart ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.carts_cart_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: carts_cartitem; Type: TABLE; Schema: public; Owner: thamjid
--

CREATE TABLE public.carts_cartitem (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    is_active boolean NOT NULL,
    is_deleted boolean NOT NULL,
    quantity integer NOT NULL,
    unit_price numeric(10,2) NOT NULL,
    total_price numeric(10,2) NOT NULL,
    booking_date date,
    booking_time time without time zone,
    special_requests text,
    cart_id bigint NOT NULL,
    product_id bigint NOT NULL,
    CONSTRAINT carts_cartitem_quantity_check CHECK ((quantity >= 0))
);


ALTER TABLE public.carts_cartitem OWNER TO thamjid;

--
-- Name: carts_cartitem_id_seq; Type: SEQUENCE; Schema: public; Owner: thamjid
--

ALTER TABLE public.carts_cartitem ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.carts_cartitem_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: carts_orderdetail; Type: TABLE; Schema: public; Owner: thamjid
--

CREATE TABLE public.carts_orderdetail (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    order_number character varying(50) NOT NULL,
    customer_name character varying(200) NOT NULL,
    customer_email character varying(254) NOT NULL,
    customer_phone character varying(20) NOT NULL,
    status character varying(24) NOT NULL,
    payment_status character varying(24) NOT NULL,
    subtotal numeric(10,2) NOT NULL,
    tax numeric(10,2) NOT NULL,
    total_amount numeric(10,2) NOT NULL,
    order_date timestamp with time zone NOT NULL,
    checkout_date timestamp with time zone NOT NULL,
    fulfillment_date timestamp with time zone,
    special_instructions text,
    admin_notes text,
    cart_id bigint,
    user_id bigint NOT NULL
);


ALTER TABLE public.carts_orderdetail OWNER TO thamjid;

--
-- Name: carts_orderdetail_id_seq; Type: SEQUENCE; Schema: public; Owner: thamjid
--

ALTER TABLE public.carts_orderdetail ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.carts_orderdetail_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: carts_orderitem; Type: TABLE; Schema: public; Owner: thamjid
--

CREATE TABLE public.carts_orderitem (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    quantity integer NOT NULL,
    unit_price numeric(10,2) NOT NULL,
    total_price numeric(10,2) NOT NULL,
    status character varying(20) NOT NULL,
    order_id bigint NOT NULL,
    product_id bigint NOT NULL,
    CONSTRAINT carts_orderitem_quantity_check CHECK ((quantity >= 0))
);


ALTER TABLE public.carts_orderitem OWNER TO thamjid;

--
-- Name: carts_orderitem_id_seq; Type: SEQUENCE; Schema: public; Owner: thamjid
--

ALTER TABLE public.carts_orderitem ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.carts_orderitem_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: contacts_contactmessage; Type: TABLE; Schema: public; Owner: thamjid
--

CREATE TABLE public.contacts_contactmessage (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    first_name character varying(100) NOT NULL,
    last_name character varying(100) NOT NULL,
    email character varying(254) NOT NULL,
    phone character varying(15) NOT NULL,
    subject character varying(200) NOT NULL,
    preferred_dates character varying(512),
    number_of_guests integer,
    message text NOT NULL
);


ALTER TABLE public.contacts_contactmessage OWNER TO thamjid;

--
-- Name: contacts_contactmessage_id_seq; Type: SEQUENCE; Schema: public; Owner: thamjid
--

ALTER TABLE public.contacts_contactmessage ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.contacts_contactmessage_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: thamjid
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id bigint NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO thamjid;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: thamjid
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: thamjid
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO thamjid;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: thamjid
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: thamjid
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO thamjid;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: thamjid
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: thamjid
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO thamjid;

--
-- Name: faq_frequentlyaskedquestion; Type: TABLE; Schema: public; Owner: thamjid
--

CREATE TABLE public.faq_frequentlyaskedquestion (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    question character varying(255) NOT NULL,
    answer text NOT NULL,
    is_active boolean NOT NULL,
    is_deleted boolean NOT NULL
);


ALTER TABLE public.faq_frequentlyaskedquestion OWNER TO thamjid;

--
-- Name: faq_frequentlyaskedquestion_id_seq; Type: SEQUENCE; Schema: public; Owner: thamjid
--

ALTER TABLE public.faq_frequentlyaskedquestion ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.faq_frequentlyaskedquestion_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: products_advertisement; Type: TABLE; Schema: public; Owner: thamjid
--

CREATE TABLE public.products_advertisement (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    is_active boolean NOT NULL,
    is_deleted boolean NOT NULL,
    title character varying(256) NOT NULL,
    file character varying(256),
    link character varying(200)
);


ALTER TABLE public.products_advertisement OWNER TO thamjid;

--
-- Name: products_advertisement_id_seq; Type: SEQUENCE; Schema: public; Owner: thamjid
--

ALTER TABLE public.products_advertisement ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.products_advertisement_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: products_categories; Type: TABLE; Schema: public; Owner: thamjid
--

CREATE TABLE public.products_categories (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    is_active boolean NOT NULL,
    is_deleted boolean NOT NULL,
    name character varying(40) NOT NULL,
    slug character varying(50) NOT NULL,
    description text,
    icon character varying(256)
);


ALTER TABLE public.products_categories OWNER TO thamjid;

--
-- Name: products_categories_id_seq; Type: SEQUENCE; Schema: public; Owner: thamjid
--

ALTER TABLE public.products_categories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.products_categories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: products_comment; Type: TABLE; Schema: public; Owner: thamjid
--

CREATE TABLE public.products_comment (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    is_active boolean NOT NULL,
    is_deleted boolean NOT NULL,
    rating smallint NOT NULL,
    message character varying(256) NOT NULL,
    object_id integer NOT NULL,
    author_id bigint NOT NULL,
    content_type_id integer NOT NULL,
    CONSTRAINT products_comment_object_id_check CHECK ((object_id >= 0)),
    CONSTRAINT products_comment_rating_check CHECK ((rating >= 0))
);


ALTER TABLE public.products_comment OWNER TO thamjid;

--
-- Name: products_comment_id_seq; Type: SEQUENCE; Schema: public; Owner: thamjid
--

ALTER TABLE public.products_comment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.products_comment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: products_favorite; Type: TABLE; Schema: public; Owner: thamjid
--

CREATE TABLE public.products_favorite (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    product_id bigint NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.products_favorite OWNER TO thamjid;

--
-- Name: products_favorite_id_seq; Type: SEQUENCE; Schema: public; Owner: thamjid
--

ALTER TABLE public.products_favorite ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.products_favorite_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: products_file; Type: TABLE; Schema: public; Owner: thamjid
--

CREATE TABLE public.products_file (
    id bigint NOT NULL,
    images character varying(256) NOT NULL,
    product_id bigint NOT NULL
);


ALTER TABLE public.products_file OWNER TO thamjid;

--
-- Name: products_file_id_seq; Type: SEQUENCE; Schema: public; Owner: thamjid
--

ALTER TABLE public.products_file ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.products_file_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: products_product; Type: TABLE; Schema: public; Owner: thamjid
--

CREATE TABLE public.products_product (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    is_active boolean NOT NULL,
    is_deleted boolean NOT NULL,
    name character varying(40) NOT NULL,
    slug character varying(50) NOT NULL,
    synopsis text,
    description text,
    price numeric(10,2) NOT NULL,
    "time" integer NOT NULL,
    policy text,
    availability character varying(20) NOT NULL,
    stock_available integer NOT NULL
);


ALTER TABLE public.products_product OWNER TO thamjid;

--
-- Name: products_product_category; Type: TABLE; Schema: public; Owner: thamjid
--

CREATE TABLE public.products_product_category (
    id bigint NOT NULL,
    product_id bigint NOT NULL,
    categories_id bigint NOT NULL
);


ALTER TABLE public.products_product_category OWNER TO thamjid;

--
-- Name: products_product_category_id_seq; Type: SEQUENCE; Schema: public; Owner: thamjid
--

ALTER TABLE public.products_product_category ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.products_product_category_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: products_product_id_seq; Type: SEQUENCE; Schema: public; Owner: thamjid
--

ALTER TABLE public.products_product ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.products_product_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: thamjid
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: thamjid
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: thamjid
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	2	add_permission
6	Can change permission	2	change_permission
7	Can delete permission	2	delete_permission
8	Can view permission	2	view_permission
9	Can add group	3	add_group
10	Can change group	3	change_group
11	Can delete group	3	delete_group
12	Can view group	3	view_group
13	Can add content type	4	add_contenttype
14	Can change content type	4	change_contenttype
15	Can delete content type	4	delete_contenttype
16	Can view content type	4	view_contenttype
17	Can add session	5	add_session
18	Can change session	5	change_session
19	Can delete session	5	delete_session
20	Can view session	5	view_session
21	Can add user	6	add_user
22	Can change user	6	change_user
23	Can delete user	6	delete_user
24	Can view user	6	view_user
25	Can add advertisement	7	add_advertisement
26	Can change advertisement	7	change_advertisement
27	Can delete advertisement	7	delete_advertisement
28	Can view advertisement	7	view_advertisement
29	Can add product	8	add_product
30	Can change product	8	change_product
31	Can delete product	8	delete_product
32	Can view product	8	view_product
33	Can add file	9	add_file
34	Can change file	9	change_file
35	Can delete file	9	delete_file
36	Can view file	9	view_file
37	Can add comment	10	add_comment
38	Can change comment	10	change_comment
39	Can delete comment	10	delete_comment
40	Can view comment	10	view_comment
41	Can add favorite	11	add_favorite
42	Can change favorite	11	change_favorite
43	Can delete favorite	11	delete_favorite
44	Can view favorite	11	view_favorite
45	Can add contact message	12	add_contactmessage
46	Can change contact message	12	change_contactmessage
47	Can delete contact message	12	delete_contactmessage
48	Can view contact message	12	view_contactmessage
49	Can add booking	13	add_booking
50	Can change booking	13	change_booking
51	Can delete booking	13	delete_booking
52	Can view booking	13	view_booking
53	Can add payment	14	add_payment
54	Can change payment	14	change_payment
55	Can delete payment	14	delete_payment
56	Can view payment	14	view_payment
57	Can add cart	15	add_cart
58	Can change cart	15	change_cart
59	Can delete cart	15	delete_cart
60	Can view cart	15	view_cart
61	Can add cart item	16	add_cartitem
62	Can change cart item	16	change_cartitem
63	Can delete cart item	16	delete_cartitem
64	Can view cart item	16	view_cartitem
65	Can add order detail	17	add_orderdetail
66	Can change order detail	17	change_orderdetail
67	Can delete order detail	17	delete_orderdetail
68	Can view order detail	17	view_orderdetail
69	Can add order item	18	add_orderitem
70	Can change order item	18	change_orderitem
71	Can delete order item	18	delete_orderitem
72	Can view order item	18	view_orderitem
73	Can add categories	19	add_categories
74	Can change categories	19	change_categories
75	Can delete categories	19	delete_categories
76	Can view categories	19	view_categories
77	Can add frequently asked question	20	add_frequentlyaskedquestion
78	Can change frequently asked question	20	change_frequentlyaskedquestion
79	Can delete frequently asked question	20	delete_frequentlyaskedquestion
80	Can view frequently asked question	20	view_frequentlyaskedquestion
\.


--
-- Data for Name: authentication_user; Type: TABLE DATA; Schema: public; Owner: thamjid
--

COPY public.authentication_user (id, password, last_login, is_superuser, is_active, is_deleted, username, full_name, email, phone, gender, avatar, is_staff, reset_token) FROM stdin;
2	pbkdf2_sha256$600000$zAIpPkfHT59blNDdmjQ06e$/NEliCXgyDas2HPg0Fi6UWYYO1MW0yZigwc66WFSQcM=	\N	f	t	f	thamjid-aqary	Thamjid M	thamjid@aqaryint.com	0527627117	\N		f	\N
3	pbkdf2_sha256$600000$vlnJOReCmHZRavQ5U80bW7$6CbXEvnyp62CDV+tAmITZ/F9jn7rec7/nP56/SDteiI=	\N	f	t	f	thachu	Thamjid Aqary	thamjid+1@aqaryint.com	+971527627117	\N		f	\N
1	pbkdf2_sha256$600000$4QvnR0iNPJoUi4Uo2bN6in$Qg67jXRwFSRH1syTac4SMnhmSKsn/ImbzgJ+x0o9XRQ=	2026-01-06 09:27:37.568575+00	t	t	f		Thamjid Mannarayil	thachuthamjid@gmail.com		M		t	\N
\.


--
-- Data for Name: authentication_user_groups; Type: TABLE DATA; Schema: public; Owner: thamjid
--

COPY public.authentication_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- Data for Name: authentication_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: thamjid
--

COPY public.authentication_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- Data for Name: bookings_booking; Type: TABLE DATA; Schema: public; Owner: thamjid
--

COPY public.bookings_booking (id, created_at, updated_at, is_active, is_deleted, booking_number, booking_date, booking_time, number_of_products, status, payment_status, subtotal, tax, total_amount, special_requests, admin_notes, order_id, user_id) FROM stdin;
9	2026-01-07 12:39:21.756054+00	2026-01-07 12:39:21.758582+00	t	f	BK-20260107-4B0D87F4	2026-01-07	12:39:21.755143	6	pending	initiated	589.94	29.50	619.44	tu,ultulfkfkrykryktuk	\N	10	2
\.


--
-- Data for Name: bookings_payment; Type: TABLE DATA; Schema: public; Owner: thamjid
--

COPY public.bookings_payment (id, created_at, updated_at, amount, payment_method, payment_status, transaction_id, session_id, payment_date, notes, booking_id) FROM stdin;
9	2026-01-07 12:39:21.762865+00	2026-01-07 12:39:21.762873+00	619.44	online	initiated	\N	cs_test_b1RlwFtblhijTifTwMQZy8XzOUCfGF4gIm9tfIiHLDSsxdtPFEudGXEZ5Z	2026-01-07 12:39:21.762885+00	Stripe payment initiated from cart checkout.	9
\.


--
-- Data for Name: carts_cart; Type: TABLE DATA; Schema: public; Owner: thamjid
--

COPY public.carts_cart (id, created_at, updated_at, is_active, is_deleted, session_id, status, subtotal, tax, total_amount, expires_at, last_activity, user_id) FROM stdin;
1	2025-12-30 12:06:23.104221+00	2026-01-07 12:39:33.005155+00	t	f	\N	closed	589.94	29.50	619.44	\N	2026-01-07 12:39:33.005159+00	2
2	2026-01-07 12:39:33.004868+00	2026-01-07 12:39:33.004879+00	t	f	\N	open	0.00	0.00	0.00	\N	2026-01-07 12:39:33.004981+00	2
\.


--
-- Data for Name: carts_cartitem; Type: TABLE DATA; Schema: public; Owner: thamjid
--

COPY public.carts_cartitem (id, created_at, updated_at, is_active, is_deleted, quantity, unit_price, total_price, booking_date, booking_time, special_requests, cart_id, product_id) FROM stdin;
8	2026-01-07 10:51:17.09442+00	2026-01-07 11:43:09.306531+00	t	f	1	129.99	129.99	2026-01-07	\N	Size: One Size, Color: Default	1	2
6	2026-01-07 10:50:52.680892+00	2026-01-07 12:28:49.440707+00	t	f	3	99.99	299.97	2026-01-07	\N	Size: One Size, Color: Default	1	3
7	2026-01-07 10:51:10.576143+00	2026-01-07 12:28:50.67439+00	t	f	2	79.99	159.98	2026-01-07	\N	Size: One Size, Color: Default	1	4
\.


--
-- Data for Name: carts_orderdetail; Type: TABLE DATA; Schema: public; Owner: thamjid
--

COPY public.carts_orderdetail (id, created_at, updated_at, order_number, customer_name, customer_email, customer_phone, status, payment_status, subtotal, tax, total_amount, order_date, checkout_date, fulfillment_date, special_instructions, admin_notes, cart_id, user_id) FROM stdin;
10	2026-01-07 12:39:21.740742+00	2026-01-07 12:39:33.009373+00	ORD-20260107-7294175A	Thamjid M	thamjid@aqaryint.com	971527627117	completed	paid	589.94	29.50	619.44	2026-01-07 12:39:21.740778+00	2026-01-07 12:39:21.740457+00	2026-01-07 12:39:33.009328+00	tu,ultulfkfkrykryktuk	\N	1	2
\.


--
-- Data for Name: carts_orderitem; Type: TABLE DATA; Schema: public; Owner: thamjid
--

COPY public.carts_orderitem (id, created_at, updated_at, quantity, unit_price, total_price, status, order_id, product_id) FROM stdin;
28	2026-01-07 12:39:21.745977+00	2026-01-07 12:39:21.745988+00	3	99.99	299.97	pending	10	3
29	2026-01-07 12:39:21.748423+00	2026-01-07 12:39:21.748431+00	2	79.99	159.98	pending	10	4
30	2026-01-07 12:39:21.750548+00	2026-01-07 12:39:21.750556+00	1	129.99	129.99	pending	10	2
\.


--
-- Data for Name: contacts_contactmessage; Type: TABLE DATA; Schema: public; Owner: thamjid
--

COPY public.contacts_contactmessage (id, created_at, updated_at, first_name, last_name, email, phone, subject, preferred_dates, number_of_guests, message) FROM stdin;
1	2026-01-07 09:27:49.386766+00	2026-01-07 09:27:49.386806+00	Thamjid	Mannarayil	thamjid@aqaryint.com	+971527627117	Nothing!!	\N	\N	qwertyuioxcvbnm
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: thamjid
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
1	2025-12-27 09:44:35.205618+00	1	Classic Linen Shirt	1	[{"added": {}}, {"added": {"name": "file", "object": "Classic Linen Shirt - product_images/classic-linen-shirt1.jpg"}}, {"added": {"name": "file", "object": "Classic Linen Shirt - product_images/classic-linen-shirt2.jpg"}}, {"added": {"name": "file", "object": "Classic Linen Shirt - product_images/classic-linen-shirt3.png"}}]	8	1
2	2025-12-27 09:46:51.997621+00	2	Relaxed Linen Dress	1	[{"added": {}}, {"added": {"name": "file", "object": "Relaxed Linen Dress - product_images/relaxed-linen-dress1.jpg"}}, {"added": {"name": "file", "object": "Relaxed Linen Dress - product_images/relaxed-linen-dress2.jpg"}}, {"added": {"name": "file", "object": "Relaxed Linen Dress - product_images/relaxed-linen-dress3.jpg"}}]	8	1
3	2025-12-27 09:49:12.209731+00	3	Linen Trousers	1	[{"added": {}}, {"added": {"name": "file", "object": "Linen Trousers - product_images/linen-trousers1.jpg"}}, {"added": {"name": "file", "object": "Linen Trousers - product_images/linen-trousers2.jpg"}}, {"added": {"name": "file", "object": "Linen Trousers - product_images/linen-trousers3.jpg"}}]	8	1
4	2025-12-27 09:51:23.725753+00	4	Linen Blouse	1	[{"added": {}}, {"added": {"name": "file", "object": "Linen Blouse - product_images/linen-blouse1.png"}}, {"added": {"name": "file", "object": "Linen Blouse - product_images/linen-blouse2.jpg"}}, {"added": {"name": "file", "object": "Linen Blouse - product_images/linen-blouse3.jpg"}}]	8	1
5	2025-12-30 12:19:34.817656+00	2	Relaxed Linen Dress	2	[{"changed": {"name": "file", "object": "Relaxed Linen Dress - product_images/relaxed-linen-dress3_9KP18AZ.jpg", "fields": ["Images"]}}, {"changed": {"name": "file", "object": "Relaxed Linen Dress - product_images/relaxed-linen-dress1_SidFdxg.jpg", "fields": ["Images"]}}]	8	1
6	2026-01-06 09:42:23.845833+00	1	Mens Shirts	1	[{"added": {}}]	19	1
7	2026-01-06 09:43:04.592972+00	2	Women's Shirts	1	[{"added": {}}]	19	1
8	2026-01-06 09:43:37.71529+00	3	Mens Trousers	1	[{"added": {}}]	19	1
9	2026-01-06 09:44:03.976676+00	4	Accessories	1	[{"added": {}}]	19	1
10	2026-01-06 09:45:00.388922+00	4	Linen Blouse	2	[{"changed": {"fields": ["Category"]}}]	8	1
11	2026-01-06 09:45:11.070873+00	3	Linen Trousers	2	[{"changed": {"fields": ["Category"]}}]	8	1
12	2026-01-07 07:14:56.752527+00	1	What makes linen special? -> Linen is a natural fiber known for its exceptional breathability, durability, and comfort. It gets softer with each wash and has natural moisture-wicking properties, makin	1	[{"added": {}}]	20	1
13	2026-01-07 07:15:15.576356+00	2	How do I care for linen clothing? -> Linen is easy to care for. Machine wash in cold or lukewarm water with mild detergent. Tumble dry on low or line dry for best results. Linen naturally wrinkles, wh	1	[{"added": {}}]	20	1
14	2026-01-07 07:15:36.493172+00	3	What is your return policy? -> We offer a 30-day return policy on all unworn, unwashed items with original tags attached. If you're not completely satisfied with your purchase, contact our customer se	1	[{"added": {}}]	20	1
15	2026-01-07 07:15:55.700916+00	4	Do you offer international shipping? -> Yes, we ship to most countries worldwide. Shipping costs and delivery times vary by location. Free shipping is available on orders over $100 within the continen	1	[{"added": {}}]	20	1
16	2026-01-07 07:16:20.927846+00	5	How do I choose the right size? -> Each product page includes a detailed size guide. Our linen garments are designed for a relaxed, comfortable fit. If you're between sizes, we recommend sizing up for	1	[{"added": {}}]	20	1
17	2026-01-07 07:16:39.799156+00	6	Are your products sustainable? -> Sustainability is at the core of our brand. Our linen is sourced from European flax farms that practice responsible farming without harmful pesticides. The flax plant	1	[{"added": {}}]	20	1
18	2026-01-07 07:33:09.157178+00	6	Are your products sustainable?! -> Sustainability is at the core of our brand. Our linen is sourced from European flax farms that practice responsible farming without harmful pesticides. The flax plan	2	[{"changed": {"fields": ["Question"]}}]	20	1
19	2026-01-07 11:45:24.145909+00	3	Linen Trousers	2	[{"changed": {"name": "file", "object": "Linen Trousers - product_images/linen-trousers3_iAd9cGg.jpg", "fields": ["Images"]}}, {"changed": {"name": "file", "object": "Linen Trousers - product_images/linen-trousers1_a7dvtML.jpg", "fields": ["Images"]}}]	8	1
20	2026-01-07 12:16:40.692989+00	6	Booking #BK-20260107-A3661882 - Thamjid M	3		13	1
21	2026-01-07 12:16:40.696545+00	5	Booking #BK-20260107-922EF7F5 - Thamjid M	3		13	1
22	2026-01-07 12:16:40.698545+00	4	Booking #BK-20260107-3DE5571C - Thamjid M	3		13	1
23	2026-01-07 12:16:40.700461+00	3	Booking #BK-20260107-9806DFB7 - Thamjid M	3		13	1
24	2026-01-07 12:16:40.702516+00	2	Booking #BK-20260107-E3678AA6 - Thamjid M	3		13	1
25	2026-01-07 12:16:40.704498+00	1	Booking #BK-20260107-B21C18D9 - Thamjid M	3		13	1
26	2026-01-07 12:16:50.551551+00	7	Order #ORD-20260107-3E403DDF - Thamjid M	3		17	1
27	2026-01-07 12:16:50.563762+00	6	Order #ORD-20260107-884DC533 - Thamjid M	3		17	1
28	2026-01-07 12:16:50.565756+00	5	Order #ORD-20260107-CDA26577 - Thamjid M	3		17	1
29	2026-01-07 12:16:50.567664+00	4	Order #ORD-20260107-DDDFB629 - Thamjid M	3		17	1
30	2026-01-07 12:16:50.569647+00	3	Order #ORD-20260107-9833A114 - Thamjid M	3		17	1
31	2026-01-07 12:16:50.571721+00	2	Order #ORD-20260107-31D3D2A1 - Thamjid M	3		17	1
32	2026-01-07 12:16:50.573719+00	1	Order #ORD-20260107-0871F1C2 - Thamjid M	3		17	1
33	2026-01-07 12:21:37.186313+00	7	Booking #BK-20260107-D7D31E19 - Thamjid M	3		13	1
34	2026-01-07 12:21:48.943918+00	8	Order #ORD-20260107-83491621 - Thamjid M	3		17	1
35	2026-01-07 12:38:53.953521+00	8	Booking #BK-20260107-F0D16EF7 - Thamjid M	3		13	1
36	2026-01-07 12:39:01.572362+00	9	Order #ORD-20260107-3952BDD1 - Thamjid M	3		17	1
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: thamjid
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	permission
3	auth	group
4	contenttypes	contenttype
5	sessions	session
6	authentication	user
7	products	advertisement
8	products	product
9	products	file
10	products	comment
11	products	favorite
12	contacts	contactmessage
13	bookings	booking
14	bookings	payment
15	carts	cart
16	carts	cartitem
17	carts	orderdetail
18	carts	orderitem
19	products	categories
20	faq	frequentlyaskedquestion
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: thamjid
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2025-12-27 09:14:31.753145+00
2	contenttypes	0002_remove_content_type_name	2025-12-27 09:14:31.758469+00
3	auth	0001_initial	2025-12-27 09:14:31.809175+00
4	auth	0002_alter_permission_name_max_length	2025-12-27 09:14:31.812928+00
5	auth	0003_alter_user_email_max_length	2025-12-27 09:14:31.816119+00
6	auth	0004_alter_user_username_opts	2025-12-27 09:14:31.819843+00
7	auth	0005_alter_user_last_login_null	2025-12-27 09:14:31.823704+00
8	auth	0006_require_contenttypes_0002	2025-12-27 09:14:31.826106+00
9	auth	0007_alter_validators_add_error_messages	2025-12-27 09:14:31.831166+00
10	auth	0008_alter_user_username_max_length	2025-12-27 09:14:31.834865+00
11	auth	0009_alter_user_last_name_max_length	2025-12-27 09:14:31.838629+00
12	auth	0010_alter_group_name_max_length	2025-12-27 09:14:31.842519+00
13	auth	0011_update_proxy_permissions	2025-12-27 09:14:31.846032+00
14	auth	0012_alter_user_first_name_max_length	2025-12-27 09:14:31.850305+00
15	authentication	0001_initial	2025-12-27 09:14:31.905054+00
16	admin	0001_initial	2025-12-27 09:14:31.931084+00
17	admin	0002_logentry_remove_auto_add	2025-12-27 09:14:31.935141+00
18	admin	0003_logentry_add_action_flag_choices	2025-12-27 09:14:31.940673+00
19	carts	0001_initial	2025-12-27 09:14:31.989349+00
20	bookings	0001_initial	2025-12-27 09:14:32.023052+00
21	bookings	0002_initial	2025-12-27 09:14:32.071829+00
22	products	0001_initial	2025-12-27 09:14:32.154711+00
23	carts	0002_initial	2025-12-27 09:14:32.286199+00
24	contacts	0001_initial	2025-12-27 09:14:32.299+00
25	sessions	0001_initial	2025-12-27 09:14:32.319576+00
26	products	0002_remove_product_create_time_remove_product_location_and_more	2025-12-27 09:38:09.019072+00
27	bookings	0003_rename_number_of_guests_booking_number_of_products	2026-01-03 07:45:11.57997+00
29	products	0003_categories_product_category	2026-01-06 09:41:27.931599+00
30	faq	0001_initial	2026-01-07 07:14:33.967054+00
31	faq	0002_frequentlyaskedquestion_is_active_and_more	2026-01-07 07:17:32.231664+00
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: thamjid
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
y7g0ba50jmnprc66vqdxugop9d3b0juc	.eJxVjEEOwiAQRe_C2hDoMC24dO8ZCMwMUjVtUtqV8e7apAvd_vfef6mYtrXGrckSR1ZnZdXpd8uJHjLtgO9pus2a5mldxqx3RR-06evM8rwc7t9BTa1-a_DBeAx96smzCQ4MAHtnsUsDOydEaLFwGSiH4KFgAQtIWQJKJ8aq9we8FTdW:1vZQZh:4_cMZBN696NM6O7MRX_fwT_B-eCWsYwyIRdBu-NgyfY	2026-01-10 09:27:01.628413+00
5pj8w7qqkxwbd4u3bi8xr440s41kdh4u	.eJxVjEEOwiAQRe_C2hDoMC24dO8ZCMwMUjVtUtqV8e7apAvd_vfef6mYtrXGrckSR1ZnZdXpd8uJHjLtgO9pus2a5mldxqx3RR-06evM8rwc7t9BTa1-a_DBeAx96smzCQ4MAHtnsUsDOydEaLFwGSiH4KFgAQtIWQJKJ8aq9we8FTdW:1vc0NF:Kiultd1q58dPb1vYW4hv8A79ypMfBdDRRAbcCvnYlLQ	2026-01-17 12:04:49.015315+00
ad4zk4o0tvnakgvkp3jlar99ayj2jg68	.eJxVjEEOwiAQRe_C2hDoMC24dO8ZCMwMUjVtUtqV8e7apAvd_vfef6mYtrXGrckSR1ZnZdXpd8uJHjLtgO9pus2a5mldxqx3RR-06evM8rwc7t9BTa1-a_DBeAx96smzCQ4MAHtnsUsDOydEaLFwGSiH4KFgAQtIWQJKJ8aq9we8FTdW:1vd3Ll:aZE9OF-6B4Oj06TftHumifr6HN2YTzGZu0y9ObrKzLQ	2026-01-20 09:27:37.570873+00
\.


--
-- Data for Name: faq_frequentlyaskedquestion; Type: TABLE DATA; Schema: public; Owner: thamjid
--

COPY public.faq_frequentlyaskedquestion (id, created_at, updated_at, question, answer, is_active, is_deleted) FROM stdin;
1	2026-01-07 07:14:56.751795+00	2026-01-07 07:14:56.751805+00	What makes linen special?	Linen is a natural fiber known for its exceptional breathability, durability, and comfort. It gets softer with each wash and has natural moisture-wicking properties, making it perfect for all seasons. Our premium European linen is sustainably sourced and crafted with care.	t	f
2	2026-01-07 07:15:15.57565+00	2026-01-07 07:15:15.575659+00	How do I care for linen clothing?	Linen is easy to care for. Machine wash in cold or lukewarm water with mild detergent. Tumble dry on low or line dry for best results. Linen naturally wrinkles, which is part of its charm, but you can iron while slightly damp if you prefer a crisp look. Always check the care label for specific instructions.	t	f
3	2026-01-07 07:15:36.492426+00	2026-01-07 07:15:36.492436+00	What is your return policy?	We offer a 30-day return policy on all unworn, unwashed items with original tags attached. If you're not completely satisfied with your purchase, contact our customer service team to initiate a return. Free return shipping is provided for defective items or wrong deliveries.	t	f
4	2026-01-07 07:15:55.700318+00	2026-01-07 07:15:55.700325+00	Do you offer international shipping?	Yes, we ship to most countries worldwide. Shipping costs and delivery times vary by location. Free shipping is available on orders over $100 within the continental US. International orders may be subject to customs fees and import duties, which are the responsibility of the customer.	t	f
5	2026-01-07 07:16:20.927159+00	2026-01-07 07:16:20.927167+00	How do I choose the right size?	Each product page includes a detailed size guide. Our linen garments are designed for a relaxed, comfortable fit. If you're between sizes, we recommend sizing up for a more relaxed look, or sizing down for a more fitted appearance. Feel free to contact our customer service team if you need personalized sizing assistance.	t	f
6	2026-01-07 07:16:39.79847+00	2026-01-07 07:33:09.156047+00	Are your products sustainable?!	Sustainability is at the core of our brand. Our linen is sourced from European flax farms that practice responsible farming without harmful pesticides. The flax plant requires minimal water and naturally regenerates the soil. We also use eco-friendly dyes and packaging materials throughout our supply chain.	t	f
\.


--
-- Data for Name: products_advertisement; Type: TABLE DATA; Schema: public; Owner: thamjid
--

COPY public.products_advertisement (id, created_at, updated_at, is_active, is_deleted, title, file, link) FROM stdin;
\.


--
-- Data for Name: products_categories; Type: TABLE DATA; Schema: public; Owner: thamjid
--

COPY public.products_categories (id, created_at, updated_at, is_active, is_deleted, name, slug, description, icon) FROM stdin;
1	2026-01-06 09:42:23.845064+00	2026-01-06 09:42:23.845075+00	t	f	Mens Shirts	mens-shirts	Various Collections of Men's Linen Shirts	
2	2026-01-06 09:43:04.592477+00	2026-01-06 09:43:04.592488+00	t	f	Women's Shirts	womens-shirts	Various Collection of women's Shirts	
3	2026-01-06 09:43:37.714831+00	2026-01-06 09:43:37.714841+00	t	f	Mens Trousers	mens-trousers	Various Collection of Men's Trousers	
4	2026-01-06 09:44:03.976281+00	2026-01-06 09:44:03.97629+00	t	f	Accessories	accessories	Various Collection of Accessories	
\.


--
-- Data for Name: products_comment; Type: TABLE DATA; Schema: public; Owner: thamjid
--

COPY public.products_comment (id, created_at, updated_at, is_active, is_deleted, rating, message, object_id, author_id, content_type_id) FROM stdin;
1	2025-12-27 09:44:35.150885+00	2025-12-27 09:44:35.150885+00	t	f	5	qwerty	4	2	8
2	2025-12-27 09:44:35.150885+00	2025-12-27 09:44:35.150885+00	t	f	2	sgshrdf	4	2	8
3	2025-12-27 09:44:35.150885+00	2025-12-27 09:44:35.150885+00	t	f	5	sasdfgh	4	2	8
4	2025-12-27 11:10:29.574526+00	2025-12-27 11:10:29.574539+00	t	f	4	This is awesome	4	2	8
5	2025-12-27 12:11:52.276681+00	2025-12-27 12:11:52.276718+00	t	f	4	gjl.h	4	2	8
6	2026-01-07 10:25:52.704172+00	2026-01-07 10:25:52.704186+00	t	f	4	\\sfshdfnfdgmn	3	2	8
7	2026-01-07 10:26:04.550709+00	2026-01-07 10:26:04.550721+00	t	f	3	sbdh	3	2	8
\.


--
-- Data for Name: products_favorite; Type: TABLE DATA; Schema: public; Owner: thamjid
--

COPY public.products_favorite (id, created_at, updated_at, product_id, user_id) FROM stdin;
10	2026-01-06 09:16:32.384403+00	2026-01-06 09:16:32.38442+00	3	2
\.


--
-- Data for Name: products_file; Type: TABLE DATA; Schema: public; Owner: thamjid
--

COPY public.products_file (id, images, product_id) FROM stdin;
1	product_images/classic-linen-shirt1.jpg	1
2	product_images/classic-linen-shirt2.jpg	1
3	product_images/classic-linen-shirt3.png	1
5	product_images/relaxed-linen-dress2.jpg	2
8	product_images/linen-trousers2.jpg	3
10	product_images/linen-blouse1.png	4
11	product_images/linen-blouse2.jpg	4
12	product_images/linen-blouse3.jpg	4
4	product_images/relaxed-linen-dress3_9KP18AZ.jpg	2
6	product_images/relaxed-linen-dress1_SidFdxg.jpg	2
7	product_images/linen-trousers3_iAd9cGg.jpg	3
9	product_images/linen-trousers1_a7dvtML.jpg	3
\.


--
-- Data for Name: products_product; Type: TABLE DATA; Schema: public; Owner: thamjid
--

COPY public.products_product (id, created_at, updated_at, is_active, is_deleted, name, slug, synopsis, description, price, "time", policy, availability, stock_available) FROM stdin;
1	2025-12-27 09:44:35.150873+00	2025-12-27 09:44:35.150885+00	t	f	Classic Linen Shirt	classic-linen-shirt	Breathable and comfortable linen shirt perfect for any occasion. Made from 100% premium European linen.	<h2>Product Description</h2>\r\n\r\n<p>Breathable and comfortable linen shirt perfect for any occasion. Made from 100% premium European linen.</p>\r\n\r\n<h3>Features:</h3>\r\n\r\n<ul>\r\n\t<li>Made from 100% premium European linen</li>\r\n\t<li>Naturally breathable and moisture-wicking</li>\r\n\t<li>Gets softer with each wash</li>\r\n\t<li>Sustainable and eco-friendly production</li>\r\n\t<li>Machine washable</li>\r\n</ul>\r\n\r\n<h2>Care Instructions</h2>\r\n\r\n<p>&bull; Machine wash cold or lukewarm (30-40&deg;C)</p>\r\n\r\n<p>&bull; Use mild detergent</p>\r\n\r\n<p>&bull; Tumble dry on low or line dry</p>\r\n\r\n<p>&bull; Iron while slightly damp if desired</p>\r\n\r\n<p>&bull; Do not bleach</p>\r\n\r\n<h3>Shipping &amp; Returns</h3>\r\n\r\n<p>Free shipping on orders over $100. Easy 30-day returns on all unworn items.</p>	89.99	0	<ul>\r\n\t<li>Free Shipping On orders over $100</li>\r\n\t<li>Quality Guarantee</li>\r\n\t<li>30-day return policy</li>\r\n</ul>	available	1000
2	2025-12-27 09:46:51.971665+00	2025-12-30 12:19:34.797096+00	t	f	Relaxed Linen Dress	relaxed-linen-dress	Elegant and comfortable linen dress with a relaxed fit. Perfect for summer days and warm evenings.	<h2>Product Description</h2>\r\n\r\n<p>Elegant and comfortable linen dress with a relaxed fit. Perfect for summer days and warm evenings.</p>\r\n\r\n<h3>Features:</h3>\r\n\r\n<ul>\r\n\t<li>Made from 100% premium European linen</li>\r\n\t<li>Naturally breathable and moisture-wicking</li>\r\n\t<li>Gets softer with each wash</li>\r\n\t<li>Sustainable and eco-friendly production</li>\r\n\t<li>Machine washable</li>\r\n</ul>\r\n\r\n<h2>Care Instructions</h2>\r\n\r\n<p>&bull; Machine wash cold or lukewarm (30-40&deg;C)</p>\r\n\r\n<p>&bull; Use mild detergent</p>\r\n\r\n<p>&bull; Tumble dry on low or line dry</p>\r\n\r\n<p>&bull; Iron while slightly damp if desired</p>\r\n\r\n<p>&bull; Do not bleach</p>\r\n\r\n<h3>Shipping &amp; Returns</h3>\r\n\r\n<p>Free shipping on orders over $100. Easy 30-day returns on all unworn items.</p>	129.99	0	<p>Free Shipping On orders over $100</p>\r\n\r\n<p>Quality Guarantee</p>\r\n\r\n<p>30-day return policy</p>	available	1000
4	2025-12-27 09:51:23.695628+00	2026-01-06 09:45:00.387275+00	t	f	Linen Blouse	linen-blouse	Lightweight linen blouse with a modern cut. Ideal for work or casual wear.	<h2>Product Description</h2>\r\n\r\n<p>Lightweight linen blouse with a modern cut. Ideal for work or casual wear.</p>\r\n\r\n<h3>Features:</h3>\r\n\r\n<ul>\r\n\t<li>Made from 100% premium European linen</li>\r\n\t<li>Naturally breathable and moisture-wicking</li>\r\n\t<li>Gets softer with each wash</li>\r\n\t<li>Sustainable and eco-friendly production</li>\r\n\t<li>Machine washable</li>\r\n</ul>\r\n\r\n<h2>Care Instructions</h2>\r\n\r\n<p>&bull; Machine wash cold or lukewarm (30-40&deg;C)</p>\r\n\r\n<p>&bull; Use mild detergent</p>\r\n\r\n<p>&bull; Tumble dry on low or line dry</p>\r\n\r\n<p>&bull; Iron while slightly damp if desired</p>\r\n\r\n<p>&bull; Do not bleach</p>\r\n\r\n<h3>Shipping &amp; Returns</h3>\r\n\r\n<p>Free shipping on orders over $100. Easy 30-day returns on all unworn items.</p>	79.99	0	<p>Free Shipping On orders over $100</p>\r\n\r\n<p>Quality Guarantee</p>\r\n\r\n<p>30-day return policy</p>	available	1000
3	2025-12-27 09:49:12.15273+00	2026-01-07 11:45:24.127184+00	t	f	Linen Trousers	linen-trousers	Comfortable and stylish linen trousers. Perfect for casual or smart-casual occasions.	<h2>Product Description</h2>\r\n\r\n<p>Comfortable and stylish linen trousers. Perfect for casual or smart-casual occasions.</p>\r\n\r\n<h3>Features:</h3>\r\n\r\n<ul>\r\n\t<li>Made from 100% premium European linen</li>\r\n\t<li>Naturally breathable and moisture-wicking</li>\r\n\t<li>Gets softer with each wash</li>\r\n\t<li>Sustainable and eco-friendly production</li>\r\n\t<li>Machine washable</li>\r\n</ul>\r\n\r\n<h2>Care Instructions</h2>\r\n\r\n<p>&bull; Machine wash cold or lukewarm (30-40&deg;C)</p>\r\n\r\n<p>&bull; Use mild detergent</p>\r\n\r\n<p>&bull; Tumble dry on low or line dry</p>\r\n\r\n<p>&bull; Iron while slightly damp if desired</p>\r\n\r\n<p>&bull; Do not bleach</p>\r\n\r\n<h3>Shipping &amp; Returns</h3>\r\n\r\n<p>Free shipping on orders over $100. Easy 30-day returns on all unworn items.</p>	99.99	0	<p>Free Shipping On orders over $100</p>\r\n\r\n<p>Quality Guarantee</p>\r\n\r\n<p>30-day return policy</p>	available	1000
\.


--
-- Data for Name: products_product_category; Type: TABLE DATA; Schema: public; Owner: thamjid
--

COPY public.products_product_category (id, product_id, categories_id) FROM stdin;
1	4	2
2	3	3
\.


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: thamjid
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: thamjid
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: thamjid
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 80, true);


--
-- Name: authentication_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: thamjid
--

SELECT pg_catalog.setval('public.authentication_user_groups_id_seq', 1, false);


--
-- Name: authentication_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: thamjid
--

SELECT pg_catalog.setval('public.authentication_user_id_seq', 3, true);


--
-- Name: authentication_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: thamjid
--

SELECT pg_catalog.setval('public.authentication_user_user_permissions_id_seq', 1, false);


--
-- Name: bookings_booking_id_seq; Type: SEQUENCE SET; Schema: public; Owner: thamjid
--

SELECT pg_catalog.setval('public.bookings_booking_id_seq', 9, true);


--
-- Name: bookings_payment_id_seq; Type: SEQUENCE SET; Schema: public; Owner: thamjid
--

SELECT pg_catalog.setval('public.bookings_payment_id_seq', 9, true);


--
-- Name: carts_cart_id_seq; Type: SEQUENCE SET; Schema: public; Owner: thamjid
--

SELECT pg_catalog.setval('public.carts_cart_id_seq', 2, true);


--
-- Name: carts_cartitem_id_seq; Type: SEQUENCE SET; Schema: public; Owner: thamjid
--

SELECT pg_catalog.setval('public.carts_cartitem_id_seq', 8, true);


--
-- Name: carts_orderdetail_id_seq; Type: SEQUENCE SET; Schema: public; Owner: thamjid
--

SELECT pg_catalog.setval('public.carts_orderdetail_id_seq', 10, true);


--
-- Name: carts_orderitem_id_seq; Type: SEQUENCE SET; Schema: public; Owner: thamjid
--

SELECT pg_catalog.setval('public.carts_orderitem_id_seq', 30, true);


--
-- Name: contacts_contactmessage_id_seq; Type: SEQUENCE SET; Schema: public; Owner: thamjid
--

SELECT pg_catalog.setval('public.contacts_contactmessage_id_seq', 1, true);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: thamjid
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 36, true);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: thamjid
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 20, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: thamjid
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 31, true);


--
-- Name: faq_frequentlyaskedquestion_id_seq; Type: SEQUENCE SET; Schema: public; Owner: thamjid
--

SELECT pg_catalog.setval('public.faq_frequentlyaskedquestion_id_seq', 6, true);


--
-- Name: products_advertisement_id_seq; Type: SEQUENCE SET; Schema: public; Owner: thamjid
--

SELECT pg_catalog.setval('public.products_advertisement_id_seq', 1, false);


--
-- Name: products_categories_id_seq; Type: SEQUENCE SET; Schema: public; Owner: thamjid
--

SELECT pg_catalog.setval('public.products_categories_id_seq', 4, true);


--
-- Name: products_comment_id_seq; Type: SEQUENCE SET; Schema: public; Owner: thamjid
--

SELECT pg_catalog.setval('public.products_comment_id_seq', 7, true);


--
-- Name: products_favorite_id_seq; Type: SEQUENCE SET; Schema: public; Owner: thamjid
--

SELECT pg_catalog.setval('public.products_favorite_id_seq', 10, true);


--
-- Name: products_file_id_seq; Type: SEQUENCE SET; Schema: public; Owner: thamjid
--

SELECT pg_catalog.setval('public.products_file_id_seq', 12, true);


--
-- Name: products_product_category_id_seq; Type: SEQUENCE SET; Schema: public; Owner: thamjid
--

SELECT pg_catalog.setval('public.products_product_category_id_seq', 2, true);


--
-- Name: products_product_id_seq; Type: SEQUENCE SET; Schema: public; Owner: thamjid
--

SELECT pg_catalog.setval('public.products_product_id_seq', 4, true);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: thamjid
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: thamjid
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: thamjid
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: thamjid
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: thamjid
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: thamjid
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: authentication_user authentication_user_email_key; Type: CONSTRAINT; Schema: public; Owner: thamjid
--

ALTER TABLE ONLY public.authentication_user
    ADD CONSTRAINT authentication_user_email_key UNIQUE (email);


--
-- Name: authentication_user_groups authentication_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: thamjid
--

ALTER TABLE ONLY public.authentication_user_groups
    ADD CONSTRAINT authentication_user_groups_pkey PRIMARY KEY (id);


--
-- Name: authentication_user_groups authentication_user_groups_user_id_group_id_8af031ac_uniq; Type: CONSTRAINT; Schema: public; Owner: thamjid
--

ALTER TABLE ONLY public.authentication_user_groups
    ADD CONSTRAINT authentication_user_groups_user_id_group_id_8af031ac_uniq UNIQUE (user_id, group_id);


--
-- Name: authentication_user authentication_user_pkey; Type: CONSTRAINT; Schema: public; Owner: thamjid
--

ALTER TABLE ONLY public.authentication_user
    ADD CONSTRAINT authentication_user_pkey PRIMARY KEY (id);


--
-- Name: authentication_user_user_permissions authentication_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: thamjid
--

ALTER TABLE ONLY public.authentication_user_user_permissions
    ADD CONSTRAINT authentication_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: authentication_user_user_permissions authentication_user_user_user_id_permission_id_ec51b09f_uniq; Type: CONSTRAINT; Schema: public; Owner: thamjid
--

ALTER TABLE ONLY public.authentication_user_user_permissions
    ADD CONSTRAINT authentication_user_user_user_id_permission_id_ec51b09f_uniq UNIQUE (user_id, permission_id);


--
-- Name: bookings_booking bookings_booking_booking_number_key; Type: CONSTRAINT; Schema: public; Owner: thamjid
--

ALTER TABLE ONLY public.bookings_booking
    ADD CONSTRAINT bookings_booking_booking_number_key UNIQUE (booking_number);


--
-- Name: bookings_booking bookings_booking_pkey; Type: CONSTRAINT; Schema: public; Owner: thamjid
--

ALTER TABLE ONLY public.bookings_booking
    ADD CONSTRAINT bookings_booking_pkey PRIMARY KEY (id);


--
-- Name: bookings_payment bookings_payment_pkey; Type: CONSTRAINT; Schema: public; Owner: thamjid
--

ALTER TABLE ONLY public.bookings_payment
    ADD CONSTRAINT bookings_payment_pkey PRIMARY KEY (id);


--
-- Name: carts_cart carts_cart_pkey; Type: CONSTRAINT; Schema: public; Owner: thamjid
--

ALTER TABLE ONLY public.carts_cart
    ADD CONSTRAINT carts_cart_pkey PRIMARY KEY (id);


--
-- Name: carts_cartitem carts_cartitem_cart_id_product_id_booki_c933b875_uniq; Type: CONSTRAINT; Schema: public; Owner: thamjid
--

ALTER TABLE ONLY public.carts_cartitem
    ADD CONSTRAINT carts_cartitem_cart_id_product_id_booki_c933b875_uniq UNIQUE (cart_id, product_id, booking_date, booking_time);


--
-- Name: carts_cartitem carts_cartitem_pkey; Type: CONSTRAINT; Schema: public; Owner: thamjid
--

ALTER TABLE ONLY public.carts_cartitem
    ADD CONSTRAINT carts_cartitem_pkey PRIMARY KEY (id);


--
-- Name: carts_orderdetail carts_orderdetail_order_number_key; Type: CONSTRAINT; Schema: public; Owner: thamjid
--

ALTER TABLE ONLY public.carts_orderdetail
    ADD CONSTRAINT carts_orderdetail_order_number_key UNIQUE (order_number);


--
-- Name: carts_orderdetail carts_orderdetail_pkey; Type: CONSTRAINT; Schema: public; Owner: thamjid
--

ALTER TABLE ONLY public.carts_orderdetail
    ADD CONSTRAINT carts_orderdetail_pkey PRIMARY KEY (id);


--
-- Name: carts_orderitem carts_orderitem_pkey; Type: CONSTRAINT; Schema: public; Owner: thamjid
--

ALTER TABLE ONLY public.carts_orderitem
    ADD CONSTRAINT carts_orderitem_pkey PRIMARY KEY (id);


--
-- Name: contacts_contactmessage contacts_contactmessage_pkey; Type: CONSTRAINT; Schema: public; Owner: thamjid
--

ALTER TABLE ONLY public.contacts_contactmessage
    ADD CONSTRAINT contacts_contactmessage_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: thamjid
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: thamjid
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: thamjid
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: thamjid
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: thamjid
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: faq_frequentlyaskedquestion faq_frequentlyaskedquestion_pkey; Type: CONSTRAINT; Schema: public; Owner: thamjid
--

ALTER TABLE ONLY public.faq_frequentlyaskedquestion
    ADD CONSTRAINT faq_frequentlyaskedquestion_pkey PRIMARY KEY (id);


--
-- Name: products_advertisement products_advertisement_pkey; Type: CONSTRAINT; Schema: public; Owner: thamjid
--

ALTER TABLE ONLY public.products_advertisement
    ADD CONSTRAINT products_advertisement_pkey PRIMARY KEY (id);


--
-- Name: products_categories products_categories_pkey; Type: CONSTRAINT; Schema: public; Owner: thamjid
--

ALTER TABLE ONLY public.products_categories
    ADD CONSTRAINT products_categories_pkey PRIMARY KEY (id);


--
-- Name: products_categories products_categories_slug_key; Type: CONSTRAINT; Schema: public; Owner: thamjid
--

ALTER TABLE ONLY public.products_categories
    ADD CONSTRAINT products_categories_slug_key UNIQUE (slug);


--
-- Name: products_comment products_comment_pkey; Type: CONSTRAINT; Schema: public; Owner: thamjid
--

ALTER TABLE ONLY public.products_comment
    ADD CONSTRAINT products_comment_pkey PRIMARY KEY (id);


--
-- Name: products_favorite products_favorite_pkey; Type: CONSTRAINT; Schema: public; Owner: thamjid
--

ALTER TABLE ONLY public.products_favorite
    ADD CONSTRAINT products_favorite_pkey PRIMARY KEY (id);


--
-- Name: products_favorite products_favorite_user_id_product_id_daf9efdd_uniq; Type: CONSTRAINT; Schema: public; Owner: thamjid
--

ALTER TABLE ONLY public.products_favorite
    ADD CONSTRAINT products_favorite_user_id_product_id_daf9efdd_uniq UNIQUE (user_id, product_id);


--
-- Name: products_file products_file_pkey; Type: CONSTRAINT; Schema: public; Owner: thamjid
--

ALTER TABLE ONLY public.products_file
    ADD CONSTRAINT products_file_pkey PRIMARY KEY (id);


--
-- Name: products_product_category products_product_categor_product_id_categories_id_60d2e800_uniq; Type: CONSTRAINT; Schema: public; Owner: thamjid
--

ALTER TABLE ONLY public.products_product_category
    ADD CONSTRAINT products_product_categor_product_id_categories_id_60d2e800_uniq UNIQUE (product_id, categories_id);


--
-- Name: products_product_category products_product_category_pkey; Type: CONSTRAINT; Schema: public; Owner: thamjid
--

ALTER TABLE ONLY public.products_product_category
    ADD CONSTRAINT products_product_category_pkey PRIMARY KEY (id);


--
-- Name: products_product products_product_pkey; Type: CONSTRAINT; Schema: public; Owner: thamjid
--

ALTER TABLE ONLY public.products_product
    ADD CONSTRAINT products_product_pkey PRIMARY KEY (id);


--
-- Name: products_product products_product_slug_key; Type: CONSTRAINT; Schema: public; Owner: thamjid
--

ALTER TABLE ONLY public.products_product
    ADD CONSTRAINT products_product_slug_key UNIQUE (slug);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: thamjid
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: thamjid
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: thamjid
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: thamjid
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: authentication_user_email_2220eff5_like; Type: INDEX; Schema: public; Owner: thamjid
--

CREATE INDEX authentication_user_email_2220eff5_like ON public.authentication_user USING btree (email varchar_pattern_ops);


--
-- Name: authentication_user_groups_group_id_6b5c44b7; Type: INDEX; Schema: public; Owner: thamjid
--

CREATE INDEX authentication_user_groups_group_id_6b5c44b7 ON public.authentication_user_groups USING btree (group_id);


--
-- Name: authentication_user_groups_user_id_30868577; Type: INDEX; Schema: public; Owner: thamjid
--

CREATE INDEX authentication_user_groups_user_id_30868577 ON public.authentication_user_groups USING btree (user_id);


--
-- Name: authentication_user_user_permissions_permission_id_ea6be19a; Type: INDEX; Schema: public; Owner: thamjid
--

CREATE INDEX authentication_user_user_permissions_permission_id_ea6be19a ON public.authentication_user_user_permissions USING btree (permission_id);


--
-- Name: authentication_user_user_permissions_user_id_736ebf7e; Type: INDEX; Schema: public; Owner: thamjid
--

CREATE INDEX authentication_user_user_permissions_user_id_736ebf7e ON public.authentication_user_user_permissions USING btree (user_id);


--
-- Name: bookings_bo_booking_03d631_idx; Type: INDEX; Schema: public; Owner: thamjid
--

CREATE INDEX bookings_bo_booking_03d631_idx ON public.bookings_booking USING btree (booking_number);


--
-- Name: bookings_bo_created_7d6386_idx; Type: INDEX; Schema: public; Owner: thamjid
--

CREATE INDEX bookings_bo_created_7d6386_idx ON public.bookings_booking USING btree (created_at DESC);


--
-- Name: bookings_bo_status_233e96_idx; Type: INDEX; Schema: public; Owner: thamjid
--

CREATE INDEX bookings_bo_status_233e96_idx ON public.bookings_booking USING btree (status);


--
-- Name: bookings_bo_user_id_0e7f91_idx; Type: INDEX; Schema: public; Owner: thamjid
--

CREATE INDEX bookings_bo_user_id_0e7f91_idx ON public.bookings_booking USING btree (user_id);


--
-- Name: bookings_booking_booking_number_a11a19da_like; Type: INDEX; Schema: public; Owner: thamjid
--

CREATE INDEX bookings_booking_booking_number_a11a19da_like ON public.bookings_booking USING btree (booking_number varchar_pattern_ops);


--
-- Name: bookings_booking_order_id_aedabed9; Type: INDEX; Schema: public; Owner: thamjid
--

CREATE INDEX bookings_booking_order_id_aedabed9 ON public.bookings_booking USING btree (order_id);


--
-- Name: bookings_booking_user_id_834dfc23; Type: INDEX; Schema: public; Owner: thamjid
--

CREATE INDEX bookings_booking_user_id_834dfc23 ON public.bookings_booking USING btree (user_id);


--
-- Name: bookings_payment_booking_id_0afdaed6; Type: INDEX; Schema: public; Owner: thamjid
--

CREATE INDEX bookings_payment_booking_id_0afdaed6 ON public.bookings_payment USING btree (booking_id);


--
-- Name: carts_cart_last_ac_caa6b1_idx; Type: INDEX; Schema: public; Owner: thamjid
--

CREATE INDEX carts_cart_last_ac_caa6b1_idx ON public.carts_cart USING btree (last_activity DESC);


--
-- Name: carts_cart_session_431d0f_idx; Type: INDEX; Schema: public; Owner: thamjid
--

CREATE INDEX carts_cart_session_431d0f_idx ON public.carts_cart USING btree (session_id, status);


--
-- Name: carts_cart_user_id_18332a_idx; Type: INDEX; Schema: public; Owner: thamjid
--

CREATE INDEX carts_cart_user_id_18332a_idx ON public.carts_cart USING btree (user_id, status);


--
-- Name: carts_cart_user_id_bd0756c7; Type: INDEX; Schema: public; Owner: thamjid
--

CREATE INDEX carts_cart_user_id_bd0756c7 ON public.carts_cart USING btree (user_id);


--
-- Name: carts_cartitem_cart_id_9cb0a756; Type: INDEX; Schema: public; Owner: thamjid
--

CREATE INDEX carts_cartitem_cart_id_9cb0a756 ON public.carts_cartitem USING btree (cart_id);


--
-- Name: carts_cartitem_product_id_acd010e4; Type: INDEX; Schema: public; Owner: thamjid
--

CREATE INDEX carts_cartitem_product_id_acd010e4 ON public.carts_cartitem USING btree (product_id);


--
-- Name: carts_order_order_d_2ab6a0_idx; Type: INDEX; Schema: public; Owner: thamjid
--

CREATE INDEX carts_order_order_d_2ab6a0_idx ON public.carts_orderdetail USING btree (order_date DESC);


--
-- Name: carts_order_order_n_45ddf3_idx; Type: INDEX; Schema: public; Owner: thamjid
--

CREATE INDEX carts_order_order_n_45ddf3_idx ON public.carts_orderdetail USING btree (order_number);


--
-- Name: carts_order_payment_69e45d_idx; Type: INDEX; Schema: public; Owner: thamjid
--

CREATE INDEX carts_order_payment_69e45d_idx ON public.carts_orderdetail USING btree (payment_status);


--
-- Name: carts_order_status_a6bb5b_idx; Type: INDEX; Schema: public; Owner: thamjid
--

CREATE INDEX carts_order_status_a6bb5b_idx ON public.carts_orderdetail USING btree (status);


--
-- Name: carts_order_user_id_c21abd_idx; Type: INDEX; Schema: public; Owner: thamjid
--

CREATE INDEX carts_order_user_id_c21abd_idx ON public.carts_orderdetail USING btree (user_id);


--
-- Name: carts_orderdetail_cart_id_7813d6fc; Type: INDEX; Schema: public; Owner: thamjid
--

CREATE INDEX carts_orderdetail_cart_id_7813d6fc ON public.carts_orderdetail USING btree (cart_id);


--
-- Name: carts_orderdetail_order_number_f2b27637_like; Type: INDEX; Schema: public; Owner: thamjid
--

CREATE INDEX carts_orderdetail_order_number_f2b27637_like ON public.carts_orderdetail USING btree (order_number varchar_pattern_ops);


--
-- Name: carts_orderdetail_user_id_c39339e6; Type: INDEX; Schema: public; Owner: thamjid
--

CREATE INDEX carts_orderdetail_user_id_c39339e6 ON public.carts_orderdetail USING btree (user_id);


--
-- Name: carts_orderitem_order_id_a7a4df7c; Type: INDEX; Schema: public; Owner: thamjid
--

CREATE INDEX carts_orderitem_order_id_a7a4df7c ON public.carts_orderitem USING btree (order_id);


--
-- Name: carts_orderitem_product_id_20621166; Type: INDEX; Schema: public; Owner: thamjid
--

CREATE INDEX carts_orderitem_product_id_20621166 ON public.carts_orderitem USING btree (product_id);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: thamjid
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: thamjid
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: thamjid
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: thamjid
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: products_categories_slug_c0342696_like; Type: INDEX; Schema: public; Owner: thamjid
--

CREATE INDEX products_categories_slug_c0342696_like ON public.products_categories USING btree (slug varchar_pattern_ops);


--
-- Name: products_comment_author_id_c88d73d4; Type: INDEX; Schema: public; Owner: thamjid
--

CREATE INDEX products_comment_author_id_c88d73d4 ON public.products_comment USING btree (author_id);


--
-- Name: products_comment_content_type_id_4f6aaf88; Type: INDEX; Schema: public; Owner: thamjid
--

CREATE INDEX products_comment_content_type_id_4f6aaf88 ON public.products_comment USING btree (content_type_id);


--
-- Name: products_favorite_product_id_f8265054; Type: INDEX; Schema: public; Owner: thamjid
--

CREATE INDEX products_favorite_product_id_f8265054 ON public.products_favorite USING btree (product_id);


--
-- Name: products_favorite_user_id_cd8466da; Type: INDEX; Schema: public; Owner: thamjid
--

CREATE INDEX products_favorite_user_id_cd8466da ON public.products_favorite USING btree (user_id);


--
-- Name: products_file_product_id_fff42171; Type: INDEX; Schema: public; Owner: thamjid
--

CREATE INDEX products_file_product_id_fff42171 ON public.products_file USING btree (product_id);


--
-- Name: products_product_category_categories_id_2bff6f94; Type: INDEX; Schema: public; Owner: thamjid
--

CREATE INDEX products_product_category_categories_id_2bff6f94 ON public.products_product_category USING btree (categories_id);


--
-- Name: products_product_category_product_id_08fb2842; Type: INDEX; Schema: public; Owner: thamjid
--

CREATE INDEX products_product_category_product_id_08fb2842 ON public.products_product_category USING btree (product_id);


--
-- Name: products_product_slug_70d3148d_like; Type: INDEX; Schema: public; Owner: thamjid
--

CREATE INDEX products_product_slug_70d3148d_like ON public.products_product USING btree (slug varchar_pattern_ops);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: thamjid
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: thamjid
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: thamjid
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: authentication_user_user_permissions authentication_user__permission_id_ea6be19a_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: thamjid
--

ALTER TABLE ONLY public.authentication_user_user_permissions
    ADD CONSTRAINT authentication_user__permission_id_ea6be19a_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: authentication_user_groups authentication_user__user_id_30868577_fk_authentic; Type: FK CONSTRAINT; Schema: public; Owner: thamjid
--

ALTER TABLE ONLY public.authentication_user_groups
    ADD CONSTRAINT authentication_user__user_id_30868577_fk_authentic FOREIGN KEY (user_id) REFERENCES public.authentication_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: authentication_user_user_permissions authentication_user__user_id_736ebf7e_fk_authentic; Type: FK CONSTRAINT; Schema: public; Owner: thamjid
--

ALTER TABLE ONLY public.authentication_user_user_permissions
    ADD CONSTRAINT authentication_user__user_id_736ebf7e_fk_authentic FOREIGN KEY (user_id) REFERENCES public.authentication_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: authentication_user_groups authentication_user_groups_group_id_6b5c44b7_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: thamjid
--

ALTER TABLE ONLY public.authentication_user_groups
    ADD CONSTRAINT authentication_user_groups_group_id_6b5c44b7_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: bookings_booking bookings_booking_order_id_aedabed9_fk_carts_orderdetail_id; Type: FK CONSTRAINT; Schema: public; Owner: thamjid
--

ALTER TABLE ONLY public.bookings_booking
    ADD CONSTRAINT bookings_booking_order_id_aedabed9_fk_carts_orderdetail_id FOREIGN KEY (order_id) REFERENCES public.carts_orderdetail(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: bookings_booking bookings_booking_user_id_834dfc23_fk_authentication_user_id; Type: FK CONSTRAINT; Schema: public; Owner: thamjid
--

ALTER TABLE ONLY public.bookings_booking
    ADD CONSTRAINT bookings_booking_user_id_834dfc23_fk_authentication_user_id FOREIGN KEY (user_id) REFERENCES public.authentication_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: bookings_payment bookings_payment_booking_id_0afdaed6_fk_bookings_booking_id; Type: FK CONSTRAINT; Schema: public; Owner: thamjid
--

ALTER TABLE ONLY public.bookings_payment
    ADD CONSTRAINT bookings_payment_booking_id_0afdaed6_fk_bookings_booking_id FOREIGN KEY (booking_id) REFERENCES public.bookings_booking(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: carts_cart carts_cart_user_id_bd0756c7_fk_authentication_user_id; Type: FK CONSTRAINT; Schema: public; Owner: thamjid
--

ALTER TABLE ONLY public.carts_cart
    ADD CONSTRAINT carts_cart_user_id_bd0756c7_fk_authentication_user_id FOREIGN KEY (user_id) REFERENCES public.authentication_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: carts_cartitem carts_cartitem_cart_id_9cb0a756_fk_carts_cart_id; Type: FK CONSTRAINT; Schema: public; Owner: thamjid
--

ALTER TABLE ONLY public.carts_cartitem
    ADD CONSTRAINT carts_cartitem_cart_id_9cb0a756_fk_carts_cart_id FOREIGN KEY (cart_id) REFERENCES public.carts_cart(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: carts_cartitem carts_cartitem_product_id_acd010e4_fk_products_product_id; Type: FK CONSTRAINT; Schema: public; Owner: thamjid
--

ALTER TABLE ONLY public.carts_cartitem
    ADD CONSTRAINT carts_cartitem_product_id_acd010e4_fk_products_product_id FOREIGN KEY (product_id) REFERENCES public.products_product(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: carts_orderdetail carts_orderdetail_cart_id_7813d6fc_fk_carts_cart_id; Type: FK CONSTRAINT; Schema: public; Owner: thamjid
--

ALTER TABLE ONLY public.carts_orderdetail
    ADD CONSTRAINT carts_orderdetail_cart_id_7813d6fc_fk_carts_cart_id FOREIGN KEY (cart_id) REFERENCES public.carts_cart(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: carts_orderdetail carts_orderdetail_user_id_c39339e6_fk_authentication_user_id; Type: FK CONSTRAINT; Schema: public; Owner: thamjid
--

ALTER TABLE ONLY public.carts_orderdetail
    ADD CONSTRAINT carts_orderdetail_user_id_c39339e6_fk_authentication_user_id FOREIGN KEY (user_id) REFERENCES public.authentication_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: carts_orderitem carts_orderitem_order_id_a7a4df7c_fk_carts_orderdetail_id; Type: FK CONSTRAINT; Schema: public; Owner: thamjid
--

ALTER TABLE ONLY public.carts_orderitem
    ADD CONSTRAINT carts_orderitem_order_id_a7a4df7c_fk_carts_orderdetail_id FOREIGN KEY (order_id) REFERENCES public.carts_orderdetail(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: carts_orderitem carts_orderitem_product_id_20621166_fk_products_product_id; Type: FK CONSTRAINT; Schema: public; Owner: thamjid
--

ALTER TABLE ONLY public.carts_orderitem
    ADD CONSTRAINT carts_orderitem_product_id_20621166_fk_products_product_id FOREIGN KEY (product_id) REFERENCES public.products_product(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: thamjid
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_authentication_user_id; Type: FK CONSTRAINT; Schema: public; Owner: thamjid
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_authentication_user_id FOREIGN KEY (user_id) REFERENCES public.authentication_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: products_comment products_comment_author_id_c88d73d4_fk_authentication_user_id; Type: FK CONSTRAINT; Schema: public; Owner: thamjid
--

ALTER TABLE ONLY public.products_comment
    ADD CONSTRAINT products_comment_author_id_c88d73d4_fk_authentication_user_id FOREIGN KEY (author_id) REFERENCES public.authentication_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: products_comment products_comment_content_type_id_4f6aaf88_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: thamjid
--

ALTER TABLE ONLY public.products_comment
    ADD CONSTRAINT products_comment_content_type_id_4f6aaf88_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: products_favorite products_favorite_product_id_f8265054_fk_products_product_id; Type: FK CONSTRAINT; Schema: public; Owner: thamjid
--

ALTER TABLE ONLY public.products_favorite
    ADD CONSTRAINT products_favorite_product_id_f8265054_fk_products_product_id FOREIGN KEY (product_id) REFERENCES public.products_product(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: products_favorite products_favorite_user_id_cd8466da_fk_authentication_user_id; Type: FK CONSTRAINT; Schema: public; Owner: thamjid
--

ALTER TABLE ONLY public.products_favorite
    ADD CONSTRAINT products_favorite_user_id_cd8466da_fk_authentication_user_id FOREIGN KEY (user_id) REFERENCES public.authentication_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: products_file products_file_product_id_fff42171_fk_products_product_id; Type: FK CONSTRAINT; Schema: public; Owner: thamjid
--

ALTER TABLE ONLY public.products_file
    ADD CONSTRAINT products_file_product_id_fff42171_fk_products_product_id FOREIGN KEY (product_id) REFERENCES public.products_product(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: products_product_category products_product_cat_categories_id_2bff6f94_fk_products_; Type: FK CONSTRAINT; Schema: public; Owner: thamjid
--

ALTER TABLE ONLY public.products_product_category
    ADD CONSTRAINT products_product_cat_categories_id_2bff6f94_fk_products_ FOREIGN KEY (categories_id) REFERENCES public.products_categories(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: products_product_category products_product_cat_product_id_08fb2842_fk_products_; Type: FK CONSTRAINT; Schema: public; Owner: thamjid
--

ALTER TABLE ONLY public.products_product_category
    ADD CONSTRAINT products_product_cat_product_id_08fb2842_fk_products_ FOREIGN KEY (product_id) REFERENCES public.products_product(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

\unrestrict eR8gw9mTIuUObB35tTI4h5ZQYRLLy0iPqwh21Dm6WDxRCQIoGwmFxq5aQVdv4hP

