# Generated by Django 4.2.3 on 2026-01-07 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='frequentlyaskedquestion',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='frequentlyaskedquestion',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
